[package]
name = "tokio-fluent"
version = "0.1.0"
authors = ["aoyagikouhei <aoyagi.kouhei@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
tokio = { version="^0.2", features=["tcp", "io-util"] }